-- migrate:up
CREATE TABLE singlechat (ID SERIAL PRIMARY KEY, SenderID INT64 NOT NULL REFERENCES users (ID), ReceiverID INT64 NOT NULL REFERENCES users (ID), Message VARCHAR(50) NOT NULL, Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- migrate:down
DROP TABLE IF EXISTS singlechat
